### ISSUE TITLE
Pop up doesn't show up on join

### ISSUE THREAD

**Issue by XxsjrapsxX** [isaacbarker/originsspigot#1]
i want this pop up to show up on first joining the server, it doesnt do that, i also would like for it to be a one time pick, this mod also doesnt seem to have that as possible right now, is it possible to make it so they can only use the /origins command once? as i feel that is a very needed update

**Comment by XxsjrapsxX** [comment]
also any plans to make it work for 1.19?

**Comment by isaacbarker** [comment]
I have now released v-2-2 which makes changes to ensure if you join and close the inventory you still will be reprompted when you rejoin. It also should now show up for new players. The `/origin` command is intended for operators only and they are the only people who can use that command. In theory all players should select an origin and stay with that origin. The plugin is now updated for 1.19 and can be used on spigot servers. As I can see paper is not out yet but it should also be compatible. Thanks for the feedback!
