### ISSUE TITLE
Trident throw innaccuracies with aiming

### ISSUE THREAD

**Issue by XxsjrapsxX** [isaacbarker/originsspigot#2]
the aiming of it seems really wack, it doesn actually travel straight, which is weird since its meant to go as a projectile, i suggest making it travel directly where the cursor is aimed and just allow the player to aim it as need be

**Comment by isaacbarker** [comment]
In release v-2-2 the aiming of the trident is fixed but does still go upward as that is the nature of tridents in the Minecraft game. It does however not go directly where the cursor is pointing as it is the intention for it to more in an arch and be more of a travelling tool rather than a weapon.
